### ISSUE TITLE
localtuya not working in HA 2022.4 

### ISSUE THREAD

**Issue by yousaf465** [rospogrigio/localtuya#789]
## The problem
  localtuya not working on 2022.4 beta 

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 8:06:44 PM (1 occurrences)
Last logged: 8:06:44 PM

![image](https://user-images.githubusercontent.com/83491212/161788482-cdfe81dd-d641-4114-8ba9-2725cc5df625.png)
![image](https://user-images.githubusercontent.com/83491212/161788573-4f89e2c6-903c-454e-be4d-57d0eae1316c.png)

Setup failed for custom integration localtuya: Unable to import component: cannot import name 'SPEED_HIGH' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)
```
-->

HA OS 2022.4b5
- Localtuya version: 3.2.4
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: core-2022.4.0b5
- [] Are you using the Home Assistant Tuya Cloud component ? <!-- if yes, put a x between the two [] => [x] -->
- [] Are you using the Tuya App in parallel ? <!-- if yes, put a x between the two [] => [x] -->

## Steps to reproduce
1. install 2022.4 HA 
2. localtuya doesn'r load. 
3.

## Configuration `configuration.yaml` or `config_flow`
<!--
  Fill this with the yaml or config_flow configuration of the failing device. Even if it seems unimportant to you. 
  Remove personal information and local key.
-->
```yaml

```

## Provide Home Assistant taceback/logs

```txt

```

**Comment by alexreddy78** [comment]
Same issue on todays, release 2022.4. LocalTuya is not working at all

Regards

**Comment by ElStupid** [comment]
Yes, experiencing the same problem.

**Comment by XeRiZeR** [comment]
Redownload the master from Hacs makes it work agin.

**Comment by brandonongzy** [comment]
Quick fix:
Seems like the issue is with the fan platform, if you do not use the fan platform, you may exclude it from the config flow.

in `custom_components/localtuya/const.py` line 49
change:
```
# Platforms in this list must support config flows
PLATFORMS = ["binary_sensor", "cover", "fan", "light", "sensor", "switch"]
```
to:
```
# Platforms in this list must support config flows
PLATFORMS = ["binary_sensor", "cover", "light", "sensor", "switch"]
```

**Comment by yaskad** [comment]
> Quick fix: Seems like the issue is with the fan platform, if you do not use the fan platform, you may exclude it from the config flow temporarily until a correct fix
> 
> in `custom_components/localtuya/const.py` line 49 change:
> 
> ```
> # Platforms in this list must support config flows
> PLATFORMS = ["binary_sensor", "cover", "fan", "light", "sensor", "switch"]
> ```
> 
> to:
> 
> ```
> # Platforms in this list must support config flows
> PLATFORMS = ["binary_sensor", "cover", "light", "sensor", "switch"]
> ```

Thanks for this quick and dirty workaround, my house was pitch black when local Toya stopped working haha!

**Comment by smibrandon** [comment]
Workaround worked for me!

**Comment by HVR88** [comment]
Workaround didn't work here on my install.  I only have a single Tuya inwall dimmer switch set up as a test platform and while no error is given and the integration loads, the switch can't be controlled from the UI and status doesn't update when the physical switch is manipulated.

**Comment by samuelmolinadonis** [comment]
> Thanks, this worked for my!!!!

**Comment by samuelmolinadonis** [comment]
> Quick fix: Seems like the issue is with the fan platform, if you do not use the fan platform, you may exclude it from the config flow temporarily until a correct fix
> 
> in `custom_components/localtuya/const.py` line 49 change:
> 
> ```
> # Platforms in this list must support config flows
> PLATFORMS = ["binary_sensor", "cover", "fan", "light", "sensor", "switch"]
> ```
> 
> to:
> 
> ```
> # Platforms in this list must support config flows
> PLATFORMS = ["binary_sensor", "cover", "light", "sensor", "switch"]
> ```

Thanks, this worked for my!!!

**Comment by yousaf465** [comment]
> Quick fix: Seems like the issue is with the fan platform, if you do not use the fan platform, you may exclude it from the config flow temporarily until a correct fix
> 
> in `custom_components/localtuya/const.py` line 49 change:
> 
> ```
> # Platforms in this list must support config flows
> PLATFORMS = ["binary_sensor", "cover", "fan", "light", "sensor", "switch"]
> ```
> 
> to:
> 
> ```
> # Platforms in this list must support config flows
> PLATFORMS = ["binary_sensor", "cover", "light", "sensor", "switch"]
> ```

do we have to restart after changing?

**Comment by jeremysherriff** [comment]
> do we have to restart after changing?

Yes, needs a HA restart

**Comment by yousaf465** [comment]
> Quick fix: Seems like the issue is with the fan platform, if you do not use the fan platform, you may exclude it from the config flow temporarily until a correct fix
> 
> in `custom_components/localtuya/const.py` line 49 change:
> 
> ```
> # Platforms in this list must support config flows
> PLATFORMS = ["binary_sensor", "cover", "fan", "light", "sensor", "switch"]
> ```
> 
> to:
> 
> ```
> # Platforms in this list must support config flows
> PLATFORMS = ["binary_sensor", "cover", "light", "sensor", "switch"]
> ```

working. Yayyyyy.

**Comment by arevindh** [comment]
My PM switch now has only an ON/OFF option. Voltage / Current /Current consumption attributes are missing .

**Comment by arevindh** [comment]
Seems like they remove those attributes from the switch 

https://github.com/home-assistant/core/pull/68821

```
As of this release, the attributes have been removed from the switch core entity platform, meaning the current_power_w and today_energy_kwh attributes are no longer available for the following:
```

> My PM switch now has only an ON/OFF option. Voltage / Current /Current consumption attributes are missing .

**Comment by alexreddy78** [comment]
I can also confirm, that no more attributes in switch. Have to manual set all DPs to proper sensors

**Comment by arevindh** [comment]
> I can also confirm, that no more attributes in switch. Have to manual set all DPs to proper sensors

@alexreddy78 How to set it manually?

**Comment by alexreddy78** [comment]
The same way, as you set switch. Select local Tuya in integrations, add same device, but chose domain sensor and chose proper DP. And repeat same steps for all DP like current, consumption, voltage and etc

**Comment by TomK** [comment]
I feel like it's time this plugin got a rewrite.  Using tuya iot credentials the plugin should be able to retrieve all the data required (including the "local key") from the tuya api.  Including setting up multiple entities for a single device automatically.

Does anyone know of any reasons why this wouldn't be possible?

**Comment by alexreddy78** [comment]
Sounds good, but all depends on developer side :) if they have wish to change it that way

**Comment by rcblackwell** [comment]
> Quick fix: Seems like the issue is with the fan platform, if you do not use the fan platform, you may exclude it from the config flow temporarily until a correct fix
> 
> in `custom_components/localtuya/const.py` line 49 change:

I don't see this at line 49. I see something similar, different format, at line 89. Should this read line 89?

**Comment by yousaf465** [comment]
> > Quick fix: Seems like the issue is with the fan platform, if you do not use the fan platform, you may exclude it from the config flow temporarily until a correct fix
> > in `custom_components/localtuya/const.py` **line 49** change:
> 
> I don't see this at line 49. I see something similar, different format, at line 89. Should this read line 89?

just remove fans wherever you found it

**Comment by sh00t2kill** [comment]
There are some comments saying this is fixed in master.
I have updated my HA instnace to use localtuya master, and the plugin loads but fans still dont work, unfortunately!

**Comment by eroc1990** [comment]
In my case, moving over to master did fix my issue. I'm only running a few lights through localtuya, though, so my setup isn't all that complex.

**Comment by yousaf465** [comment]
> In my case, moving over to master did fix my issue. I'm only running a few lights through localtuya, though, so my setup isn't all that complex.

any link to master?

**Comment by TomK** [comment]
My problem was that localtuya had somehow become detached from HACS, so i had not updated it in a while.  Cleaned that up, and re-installed the latest version using HACS.  Seemed to work for me.

**Comment by yousaf465** [comment]
> > > In my case, moving over to master did fix my issue. I'm only running a few lights through localtuya, though, so my setup isn't all that complex.
> > 
> > 
> > any link to master?
> 
> In HACS, if you go to Local Tuya, click the three-dot menu in the bottom-right of its card, and select redownload, you'll have a dropdown menu that gives you the option to select a version number. Below all the numbered versions is "master". Apply that, restart HA, and Local Tuya will be running on master.

HACS is working for me, showing wrong updates.

**Comment by yousaf465** [comment]
> > > > In my case, moving over to master did fix my issue. I'm only running a few lights through localtuya, though, so my setup isn't all that complex.
> > > 
> > > 
> > > any link to master?
> > 
> > 
> > In HACS, if you go to Local Tuya, click the three-dot menu in the bottom-right of its card, and select redownload, you'll have a dropdown menu that gives you the option to select a version number. Below all the numbered versions is "master". Apply that, restart HA, and Local Tuya will be running on master.
> 
> HACS is working for me, showing wrong updates.

I am already on 1.24.3 but still show 1.15 
and sonoff latest version but showing old version 
![image](https://user-images.githubusercontent.com/83491212/162243995-48ae79d2-4736-4fb9-ad4b-3537fa811f3a.png)

**Comment by TomK** [comment]
@yousaf465 sonoff is a different plugin, but i can see in the background that LocalTuya is running 3.2.3. have you tried upgrading to 3.2.4?

**Comment by yousaf465** [comment]
> @yousaf465 sonoff is a different plugin, but i can see in the background that LocalTuya is running 3.2.3. have you tried upgrading to 3.2.4?

the issue is fixed for me with the removal of a fan as mentioned by @yaskad 
I did try to upgrade but it will remain at same version.

**Comment by yousaf465** [comment]
> > the issue is fixed for me with the removal of a fan as mentioned by @yaskad I did try to upgrade but it will remain at the same version.
> 
> That's why I was saying to click the dots on the Local Tuya card,
> 
> ![image](https://user-images.githubusercontent.com/13401635/162251413-05afeb17-59f6-43b3-8b92-2e559f21255a.png)
> 
> Once there, click **Redownload**
> 
> ![image](https://user-images.githubusercontent.com/13401635/162251509-1e5f2bc3-451f-4808-8a58-dc6483dfcdbd.png)
> 
> Then in the dropdown, select "master", then the Download button.
> 
> ![image](https://user-images.githubusercontent.com/13401635/162251746-a3ed2766-859c-487a-8967-a15471b2b2c3.png)
> 
> It'll redownload Local Tuya on the Master version branch. Restart Home Assistant, and you should be all set.

I dont see a redownload option.
![Screenshot_20220407-215737_Home Assistant](https://user-images.githubusercontent.com/83491212/162257154-0338ef37-0a71-46ee-af54-b23af9c6dd72.jpg)

**Comment by eroc1990** [comment]
Does it give you that option if you select **Reinstall**?

**Comment by guy0nabuffalo** [comment]
I tried the quick fix of removing fan from the platforms it I still got the same error message.

I tired installing the master branch of localtuya and now the error message has changed to:

`Component error: localtuya - cannot import name 'CONF_FAN_DIRECTION' from 'custom_components.localtuya.const' (/config/custom_components/localtuya/const.py)`

**Comment by guy0nabuffalo** [comment]
> 

Yes I have. When I switched to the master branch, the error message changed to:
`Component error: localtuya - cannot import name 'CONF_FAN_DIRECTION' from 'custom_components.localtuya.const' (/config/custom_components/localtuya/const.py)`

I tried commenting out `CONF_FAN_DIRECTION` but the error message stays the same.

**Comment by guy0nabuffalo** [comment]
> > Have you tried swapping over to the Master branch as mentioned above? Does that resolve the issue?
> 
> `
> 
> Yes I have. When I switched to the master branch, the error message changed to: `Component error: localtuya - cannot import name 'CONF_FAN_DIRECTION' from 'custom_components.localtuya.const' (/config/custom_components/localtuya/const.py)`
> 
> I tried commenting out `CONF_FAN_DIRECTION` but the error message stays the same.

**Comment by HVR88** [comment]
> I dont see a redownload option.

The option is in the HACS component, not the integration.

**Comment by pablloarruda86** [comment]
I solved my problem adding marks(" ") in the url links:

```
- platform: generic
  name: CameraPabllo1
  username: !secret camera_user
  password: !secret camera_pass
  stream_source: rtsp://192.168.100.146:8554/unicast
  still_image_url: https://192.168.100.146/cgi-bin/currentpic.cgi
  framerate: 15
  verify_ssl: false
  scan_interval: 15
```
to

```
- platform: generic
  name: CameraPabllo1
  username: !secret camera_user
  password: !secret camera_pass
  stream_source: "rtsp://192.168.100.146:8554/unicast"
  still_image_url: "https://192.168.100.146/cgi-bin/currentpic.cgi"
  framerate: 15
  verify_ssl: false
  scan_interval: 15
```

**Comment by alangolley** [comment]
I have a few fans setup, after upgrading to the newest version of localtuya, I still had to reconnect all my fans.  They are all back online but seems as though the only service call that works for them is fan.set_percentage but you have to do 10% for low, 20% for mid and 30% for high.  None of the lovelace (sorry Dashboard) custom cards are working for the fans though.

**Comment by alangolley** [comment]
> I solved my problem adding marks(" ") in the url links:
> 
> ```
> - platform: generic
>   name: CameraPabllo1
>   username: !secret camera_user
>   password: !secret camera_pass
>   stream_source: rtsp://192.168.100.146:8554/unicast
>   still_image_url: https://192.168.100.146/cgi-bin/currentpic.cgi
>   framerate: 15
>   verify_ssl: false
>   scan_interval: 15
> ```
> 
> to
> 
> ```
> - platform: generic
>   name: CameraPabllo1
>   username: !secret camera_user
>   password: !secret camera_pass
>   stream_source: "rtsp://192.168.100.146:8554/unicast"
>   still_image_url: "https://192.168.100.146/cgi-bin/currentpic.cgi"
>   framerate: 15
>   verify_ssl: false
>   scan_interval: 15
> ```

Have a look at the version release information for 2022.4.  HomeAssistant have depreciated generic cameras in YAML config and you can now set them up in GUI Integration.  They will remove it from YAML config completely in subsequent upgrades

**Comment by HVR88** [comment]
Here you can see why the current situation makes some devices completely unusable. The device ID 1, which is necessary for basis ON/OFF on a switch or dimmer, is missing.

![Screen Shot 2022-04-08 at 9 05 05 AM](https://user-images.githubusercontent.com/33399216/162441527-ae7f59fa-b0c3-47a9-8971-53844a950346.png)

**Comment by mrJudahBella** [comment]
Hello, does anybody know if 2022.4.1 solves any of the above issues?

**Comment by yousaf465** [comment]
> Does it give you that option if you select **Reinstall**?

I am updating HACS hopefully it will fix it

**Comment by bolderbast** [comment]
Don't think it will be resolved by the Home Assistant team. It's a custom integration and from what I read on Discord, it is using parts of Home Assistant that have been deprecated for many many months. Maybe even a year already. Can't blame the Home Assistant team if this is the case. So I guess we'll have to hope that the localtuya has time to get this fixed.

**Comment by arevindh** [comment]
> Don't think it will be resolved by the Home Assistant team. It's a custom integration and from what I read on Discord, it is using parts of Home Assistant that have been deprecated for many many months. Maybe even a year already. Can't blame the Home Assistant team if this is the case. So I guess we'll have to hope that the localtuya team has time to get this fixed.

I think the same, this plugin should be fixed buy author or any contributers.

**Comment by yousaf465** [comment]
> > > Have you tried swapping over to the Master branch as mentioned above? Does that resolve the issue?
> > 
> > 
> > `
> > Yes I have. When I switched to the master branch, the error message changed to: `Component error: localtuya - cannot import name 'CONF_FAN_DIRECTION' from 'custom_components.localtuya.const' (/config/custom_components/localtuya/const.py)`
> > I tried commenting out `CONF_FAN_DIRECTION` but the error message stays the same.

simple fix. 
1. download zip 
![image](https://user-images.githubusercontent.com/83491212/162499347-f5f4e1cb-0741-437a-b9e3-4a176038ed7d.png)

2.  copy all files from localtuya-master.zip\local-tuya-master\custom_components\localtuya 
3. 
![image](https://user-images.githubusercontent.com/83491212/162499634-c22914e6-e7b7-4b95-bae7-c8f959cb6908.png)

3. paste in \custom_components\localtuya
4. don't replace any file. 
5. restart HA. 
6. enjoy.

**Comment by binarydad** [comment]
Is it recommended to pull from master for the fix (it DOES have the fix, right?) or should we wait for an official release?

Luckily I snapshot before updating so I was able to roll back after seeing this same error. 

Thanks to those involved in fixing this!

**Comment by Steve2017** [comment]
Removing the "fan" reference worked for me.  I see the developer of this branch did an update 6 days ago in the "master" so maybe it is fixed???
https://github.com/rospogrigio/localtuya

I'll give it a go later

**Comment by yousaf465** [comment]
> Is it recommended to pull from master for the fix (it DOES have the fix, right?) or should we wait for an official release?
> 
> Luckily I snapshot before updating so I was able to roll back after seeing this same error.
> 
> Thanks to those involved in fixing this!

there are two methods. Both work with 2022.4 HA
1. Use master and follow my advice without replacing the files https://github.com/rospogrigio/localtuya/issues/789#issuecomment-1093165029
2. Use any version like 3.2.3 or 3.2.4 and follow @brandonongzy's quick fix by removing fan https://github.com/rospogrigio/localtuya/issues/789#issuecomment-1090555437

**Comment by joe-sydney** [comment]
So to summarise this thread, if we run master, there are no issues running HA 2022.4, including fan? Waiting for this to resolve (and 2022.4 to stabilise) before upgrading HA

**Comment by CloCkWeRX** [comment]
@brandonongzy - would you consider editing your answer to direct people to use master instead, until we get #785 sorted?
That will ensure people don't lose their fans.

@joe-sydney - Can't promise no issues, but I'm not seeing issues with deprecated code; and we're slowly getting the occasional fixes added.

**Comment by joe-sydney** [comment]
Sounds good. Could a new release with all these fixes be cut and made available on HACS?

> @brandonongzy - would you consider editing your answer to direct people to use master instead, until we get #785 sorted? That will ensure people don't lose their fans.
> 
> @joe-sydney - Can't promise no issues, but I'm not seeing issues with deprecated code; and we're slowly getting the occasional fixes added.
> 
> @binarydad - Yes. This was fixed in #542

**Comment by sh00t2kill** [comment]
I've tried both the update and hacs, but still no fan.

Do I need to delete and re add the device?

**Comment by mrJudahBella** [comment]
> Alright, good news everyone - if you haven't already upgraded to master, selecting the 3.5.0 release should fix all SPEED_HIGH issues. You may need to redownload the repo information to see it.
> 
> This should now be closable.

👏

**Comment by Steve2017** [comment]
3.5.0 with the new HA update looks to be working for me.

Good job - thanks.

**Comment by milothomas** [comment]
Anyone else getting this error? I have tried localtuya 3.5.0 and master with Home Assistant 2022.4.2

`2022-04-12 15:29:05 ERROR (MainThread) [homeassistant.components.fan] Error while setting up localtuya platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/localtuya/common.py", line 74, in async_setup_entry
entity_class(
File "/config/custom_components/localtuya/fan.py", line 74, in __init__
self._ordered_list = self._config.get(CONF_FAN_ORDERED_LIST).split(",")
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by CloCkWeRX** [comment]
> self._ordered_list = self._config.get(CONF_FAN_ORDERED_LIST).split(",") AttributeError: 'NoneType' object has no attribute 'split'

Might be worth spinning off a new bug report for that - the code should probably tolerate having that config not yet set.

**Comment by deviant-studio** [comment]
i can't even restart my home assistant because of this error

**Comment by arevindh** [comment]
> i can't even restart my home assistant because of this error

Just delete folder and get it directly from github
